name: "build-dist"
on: # rebuild any branch changes
  push:
    paths:
      - '*'
      - '**/*'
      - '!dist/**'
    branches:
      - '*'
    tags-ignore:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2.1.5
        with:
          go-version: '1.12'
      - run: go build -v -o dist/main
      - uses: actions/upload-artifact@v2.3.1
        with:
          name: main-${{ matrix.runs-on }}
          path: dist/main
      - if: ${{ runner.os == 'Linux' }}
        run: |
          cp dist/main dist/main_linux
      - if: ${{ runner.os == 'Windows' }}
        run: |
          cp dist/main dist/main_windows.exe
      - if: ${{ runner.os == 'macOS' }}
        run: |
          cp dist/main dist/main_darwin
      - uses: ./
        with:
          create-commit: true
          commit-files: dist/main*
          commit-message: test-commit
          remote: origin
          remote-ref: refs/heads/test/${{ matrix.runs-on }}/${{ github.sha }}/${{ github.event_name }}
          fail-if-empty: true
      - run: git push origin :refs/heads/test/${{ matrix.runs-on }}/${{ github.sha }}/${{ github.event_name }}
          
  publish:
    name: Publish new action version
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2.1.0
        with:
          name: main-ubuntu-latest
      - uses: actions/download-artifact@v2.1.0
        with:
          name: main-macos-latest
      - uses: actions/download-artifact@v2.1.0
        with:
          name: main-windows-latest
      - uses: actions/download-artifact@v2.1.0
        with:
          name: main-windows-latest
      - run: |
         mkdir -p dist
         mv main-windows-latest/main dist/main_windows.exe
         mv main-macos-latest/main dist/main_darwin
         mv main-ubuntu-latest/main dist/main_linux
         git add dist
         chmod +x dist/main_*
         export INPUT_TOKEN=${{ github.token }}
         dist/main_linux